version: "3.9"
services:
  api:
    build: ../api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    volumes:
      - ../api:/app
      - ../storage:/app/storage
